name: Documentation

on: [push, pull_request]

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Set env vars
        run: |
          export REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}  # just the repo, as opposed to org/repo
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV

          export DOCKER_BINARY="docker"
          echo "DOCKER_BINARY=${DOCKER_BINARY}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0

      - name: Start Sirepo Docker container
        uses: mrakitin/start-sirepo-action@v1
        with:
          docker-binary: ${{ env.DOCKER_BINARY }}

      - name: Set up Python ${{ matrix.python-version }} with conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ env.REPOSITORY_NAME }}-py${{ matrix.python-version }}
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge

      - name: Install documentation-building requirements
        run: |
          set -vxeo pipefail
          conda env list
          mamba install -c conda-forge shadow3 srwpy pandoc
          pip install --upgrade pip wheel
          pip install -v .
          pip install -r requirements-dev.txt
          pip list
          conda list

      - name: Copy databroker config file
        run: |
          set -vxeuo pipefail
          mkdir -v -p ~/.config/databroker/
          cp examples/local.yml ~/.config/databroker/

      - name: Build Docs
        run: |
          set -vxeuo pipefail
          make -C docs/ html
          status=$?
          echo "Sirepo ${DOCKER_BINARY} container id: ${SIREPO_DOCKER_CONTAINER_ID}"
          ${DOCKER_BINARY} logs ${SIREPO_DOCKER_CONTAINER_ID}
          if [ $status -gt 0 ]; then
              exit $status
          fi

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPOSITORY_NAME }}-docs
          path: docs/build/html/
