name: Publish documentation

on:
  push:
    branches:
      - master
      # TODO: remove it before merging, it is here for testing purposes only!
      - doc-list-simulations

jobs:
  build:
    if: github.repository_owner == 'NSLS-II'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
      fail-fast: false

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Set env.REPOSITORY_NAME  # just the repo, as opposed to org/repo
        run: |
          export REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install documentation-building requirements
        run: |
          set -vxeuo pipefail
          python -m pip install -v .
          python -m pip install -r requirements-dev.txt
          python -m pip list

      - name: Build Docs
        run: make -C docs/ html

      - name: Deploy documentation to nsls-ii.github.io
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DOCUMENTATION_DEPLOY_KEY }}
          publish_branch: master
          publish_dir: ./docs/build/html
          external_repository: NSLS-II/NSLS-II.github.io
          destination_dir: ${{ env.REPOSITORY_NAME }}  # just the repo name, without the "NSLS-II/"
          keep_files: true  # Keep old files.
          force_orphan: false  # Keep git history.
