name : tests

on:
  push:
  pull_request:
  schedule:
      - cron: '00 4 * * *'  # daily at 4AM

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix: 
        python-version: [3.7, 3.8, 3.9]

      fail-fast: false
    steps:

    - uses: actions/checkout@v2

    - name: start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0

    - name: start Sirepo-Bluesky container
      run: |
        set -vxeuo pipefail
        . scripts/start_docker.sh -d
        echo $SIREPO_DOCKER_CONTAINER_ID >> $GITHUB_ENV

    - name: is Sirepo-Bluesky running?
      run: docker ps -a

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create conda environment
      run: |
        # For reference: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html.
        set -vxeuo pipefail
        source $CONDA/etc/profile.d/conda.sh
        conda create -n test -c conda-forge python=${{ matrix.python-version }} shadow3 srwpy

    - name: Install
      shell: bash -l {0}
      run: |
        # For reference: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html.
        set -vxeuo pipefail
        source $CONDA/etc/profile.d/conda.sh
        conda activate test
        conda env list
        pip install --upgrade pip wheel
        pip install .
        pip install -r requirements-dev.txt
        pip list
        conda list

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        # For reference: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html.
        set -vxeuo pipefail
        source $CONDA/etc/profile.d/conda.sh
        conda activate test
        pytest -s -vv sirepo_bluesky/tests
        status=$?
        echo "Sirepo Docker container id: ${SIREPO_DOCKER_CONTAINER_ID}"
        docker logs ${SIREPO_DOCKER_CONTAINER_ID}
        if [ $status -gt 0 ]; then
            exit $status
        fi
